package com.revature.models;

public class User {

    private int userId;
    private String username;
    private String password;
    private String email;
    private String role;

    //boilerplate code, including a no-id constructor for creating new users (id gets generated by DB)

    public User() {
        super();
    }

    public User(int userId, String username, String email, String role, String password) {
        super();
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.role = role;
        this.password = password;

    }

    //this constructor is for creating a new user - no userId, role defaults to "USER"
    public User(String username, String email, String role, String password) {
        super();
        this.username = username;
        this.email = email;
        this.role = "USER";
        this.password = password;
    }

    //this constructor is for login - only needs username and password
    public User(String username, String password) {
        super();
        this.username = username;
        this.password = password;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", email='" + email + '\'' +
                ", role='" + role + '\'' +
                '}';
    }
}
